# torchtitan Config.toml
# NOTE: this toml config is a preset for 8 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama 3 1B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10000

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"
rank_0_only = false # deprecated
distributed_mode = "local_rank_0" # all / local_rank_0 / rank_0

[model]
name = "llama3"
flavor = "1B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./torchtitan/torchtitan/datasets/tokenizer/original/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-4
lr_scheduler = "linear_warmup_linear_decay"
lr_scheduler_args = '{}'

[training]
batch_size = 8 # ideally 128
seq_len = 2048
warmup_steps = 1000  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 76293 # 10B
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = true
dataset = "slimpajama"

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 10000
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
