# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "/data/checkpoints"
description = "Llama 3 8B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10000

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"
rank_0_only = false

[model]
name = "llama3"
flavor = "8B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./torchtitan/torchtitan/datasets/tokenizer/original/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-4
lr_scheduler = "linear_warmup_linear_decay"
lr_scheduler_args = '{}'

[training]
batch_size = 8
seq_len = 2048
warmup_steps = 7000  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 130000 # 14h
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = true
dataset = "slimpajama"
dataloading_args='{"streaming": false, "verification_mode": "no_checks"}'

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 10000
model_weights_only = false
export_dtype = "float32"
async_mode = "async" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = true
enable_fsdp_float8_all_gather = true
precompute_float8_dynamic_scale_for_fsdp = true
scaling_type_input = 'dynamic'
scaling_type_weight = 'dynamic'
scaling_type_grad_output = 'dynamic'

[comm]
init_timeout_seconds = 600
train_timeout_seconds = 600
