# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs/"
description = "Llama 3 8B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10
consecutive_active_steps = 1
memory_timeline = "json.gz"
enable_memory_snapshot = true
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_tensorboard = true
save_tb_folder = "tb"
rank_0_only = false

[model]
name = "llama3"
flavor = "8B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./torchtitan/torchtitan/datasets/tokenizer/original/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 4
seq_len = 4096
warmup_steps = 50  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 15  # Want a single profile to be generated
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = true
dataset = "c4_test"

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 50
model_weights_only = false
export_dtype = "float32"
async_mode = "async" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false

[comm]
init_timeout_seconds = 600
train_timeout_seconds = 600
