# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "/data/checkpoints"
description = "Llama 3 8B training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10000

[metrics]
log_freq = 25
enable_tensorboard = true
save_tb_folder = "tb"
rank_0_only = false # deprecated
distributed_mode = "local_rank_0" # all / local_rank_0 / rank_0

[model]
name = "llama3"
flavor = "8B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./torchtitan/torchtitan/datasets/tokenizer/original/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 0.000244140625 # 2**-12
lr_scheduler = "linear_warmup_cosine_decay"
lr_scheduler_args = '{"final_scaling": 0.01}'

[training]
batch_size = 4
seq_len = 4096 # 1M token / step
warmup_steps = 2000  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 300000 # 300B token
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = true
dataset = "slimpajama"
dataloading_args='{"streaming": false, "verification_mode": "no_checks", "cache_dir": "/home/ubuntu/huggingface_cache/"}'

[experimental]
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 1500
model_weights_only = false
export_dtype = "float32"
async_mode = "async" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false

[comm]
init_timeout_seconds = 600
train_timeout_seconds = 600
