name: ci

env:
  GIT_MAIN_BRANCH: "main"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  # Run everything on main, most-recent on PR builds
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
      - name: Precommit
        uses: pre-commit/action@v3.0.0

  cpu-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup virtual environment
        run: |
          uv venv --python 3.10
      - name: Local install
        run: |
          uv pip install -e .
          uv pip install pytest
      - name: Run unit tests
        run: |
          uv run pytest tests/


  gpu-integration:
    runs-on: [self-hosted, gpu_2x]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup virtual environment
        run: |
          uv venv --python 3.10
      - name: Local install
        run: |
          uv pip install -e .
          uv pip install "nvidia-nccl-cu12>=2.23.4"
      - name: Run debug model on 1 devices
        run: |
          source .venv/bin/activate
          NGPU=1 ./run_llama_train.sh --wandb.mode offline --job.config ./train_configs/debug_model.toml
      - name: Run debug model on 2 devices
        run: |
          source .venv/bin/activate
          NGPU=2 ./run_llama_train.sh --wandb.mode offline --job.config ./train_configs/debug_model.toml
